// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_DiagonalMovementMZ","status":true,"description":"(v.1.2) Enables player to move diagonally and characters can use diagonal charset.","parameters":{"dMouse":"false","dCharset":"false","dSpeed":"100","blockDiag":"false"}}
];
